// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/coordinator/coordinator.proto

package coordinator

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*Participant         `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRequest) Reset() {
	*x = BeginRequest{}
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRequest) ProtoMessage() {}

func (x *BeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRequest.ProtoReflect.Descriptor instead.
func (*BeginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *BeginRequest) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *BeginRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type Participant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ResourceData  string                 `protobuf:"bytes,2,opt,name=resource_data,json=resourceData,proto3" json:"resource_data,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Value         int64                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *Participant) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Participant) GetResourceData() string {
	if x != nil {
		return x.ResourceData
	}
	return ""
}

func (x *Participant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Participant) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type BeginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	BranchResults []*BranchResult        `protobuf:"bytes,4,rep,name=branch_results,json=branchResults,proto3" json:"branch_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginResponse) Reset() {
	*x = BeginResponse{}
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginResponse) ProtoMessage() {}

func (x *BeginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginResponse.ProtoReflect.Descriptor instead.
func (*BeginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *BeginResponse) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

func (x *BeginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BeginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BeginResponse) GetBranchResults() []*BranchResult {
	if x != nil {
		return x.BranchResults
	}
	return nil
}

type BranchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchResult) Reset() {
	*x = BranchResult{}
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchResult) ProtoMessage() {}

func (x *BranchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchResult.ProtoReflect.Descriptor instead.
func (*BranchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *BranchResult) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *BranchResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BranchResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *CommitRequest) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *CommitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRequest) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *StatusRequest) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Xid            string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BranchStatuses []*BranchStatus        `protobuf:"bytes,3,rep,name=branch_statuses,json=branchStatuses,proto3" json:"branch_statuses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResponse) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetBranchStatuses() []*BranchStatus {
	if x != nil {
		return x.BranchStatuses
	}
	return nil
}

type BranchStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchStatus) Reset() {
	*x = BranchStatus{}
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchStatus) ProtoMessage() {}

func (x *BranchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchStatus.ProtoReflect.Descriptor instead.
func (*BranchStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *BranchStatus) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *BranchStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_proto_coordinator_coordinator_proto protoreflect.FileDescriptor

const file_api_proto_coordinator_coordinator_proto_rawDesc = "" +
	"\n" +
	"'api/proto/coordinator/coordinator.proto\x12\vcoordinator\"f\n" +
	"\fBeginRequest\x12<\n" +
	"\fparticipants\x18\x01 \x03(\v2\x18.coordinator.ParticipantR\fparticipants\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\"\x85\x01\n" +
	"\vParticipant\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12#\n" +
	"\rresource_data\x18\x02 \x01(\tR\fresourceData\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x03R\x05value\"\x93\x01\n" +
	"\rBeginResponse\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12@\n" +
	"\x0ebranch_results\x18\x04 \x03(\v2\x19.coordinator.BranchResultR\rbranchResults\"a\n" +
	"\fBranchResult\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"!\n" +
	"\rCommitRequest\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\"@\n" +
	"\x0eCommitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"!\n" +
	"\rCancelRequest\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\"@\n" +
	"\x0eCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"!\n" +
	"\rStatusRequest\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\"~\n" +
	"\x0eStatusResponse\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12B\n" +
	"\x0fbranch_statuses\x18\x03 \x03(\v2\x19.coordinator.BranchStatusR\x0ebranchStatuses\"I\n" +
	"\fBranchStatus\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x9c\x02\n" +
	"\x0eTCCCoordinator\x12>\n" +
	"\x05Begin\x12\x19.coordinator.BeginRequest\x1a\x1a.coordinator.BeginResponse\x12A\n" +
	"\x06Commit\x12\x1a.coordinator.CommitRequest\x1a\x1b.coordinator.CommitResponse\x12A\n" +
	"\x06Cancel\x12\x1a.coordinator.CancelRequest\x1a\x1b.coordinator.CancelResponse\x12D\n" +
	"\tGetStatus\x12\x1a.coordinator.StatusRequest\x1a\x1b.coordinator.StatusResponseB\x1bZ\x19tcc/api/proto/coordinatorb\x06proto3"

var (
	file_api_proto_coordinator_coordinator_proto_rawDescOnce sync.Once
	file_api_proto_coordinator_coordinator_proto_rawDescData []byte
)

func file_api_proto_coordinator_coordinator_proto_rawDescGZIP() []byte {
	file_api_proto_coordinator_coordinator_proto_rawDescOnce.Do(func() {
		file_api_proto_coordinator_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_coordinator_coordinator_proto_rawDesc), len(file_api_proto_coordinator_coordinator_proto_rawDesc)))
	})
	return file_api_proto_coordinator_coordinator_proto_rawDescData
}

var file_api_proto_coordinator_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_coordinator_coordinator_proto_goTypes = []any{
	(*BeginRequest)(nil),   // 0: coordinator.BeginRequest
	(*Participant)(nil),    // 1: coordinator.Participant
	(*BeginResponse)(nil),  // 2: coordinator.BeginResponse
	(*BranchResult)(nil),   // 3: coordinator.BranchResult
	(*CommitRequest)(nil),  // 4: coordinator.CommitRequest
	(*CommitResponse)(nil), // 5: coordinator.CommitResponse
	(*CancelRequest)(nil),  // 6: coordinator.CancelRequest
	(*CancelResponse)(nil), // 7: coordinator.CancelResponse
	(*StatusRequest)(nil),  // 8: coordinator.StatusRequest
	(*StatusResponse)(nil), // 9: coordinator.StatusResponse
	(*BranchStatus)(nil),   // 10: coordinator.BranchStatus
}
var file_api_proto_coordinator_coordinator_proto_depIdxs = []int32{
	1,  // 0: coordinator.BeginRequest.participants:type_name -> coordinator.Participant
	3,  // 1: coordinator.BeginResponse.branch_results:type_name -> coordinator.BranchResult
	10, // 2: coordinator.StatusResponse.branch_statuses:type_name -> coordinator.BranchStatus
	0,  // 3: coordinator.TCCCoordinator.Begin:input_type -> coordinator.BeginRequest
	4,  // 4: coordinator.TCCCoordinator.Commit:input_type -> coordinator.CommitRequest
	6,  // 5: coordinator.TCCCoordinator.Cancel:input_type -> coordinator.CancelRequest
	8,  // 6: coordinator.TCCCoordinator.GetStatus:input_type -> coordinator.StatusRequest
	2,  // 7: coordinator.TCCCoordinator.Begin:output_type -> coordinator.BeginResponse
	5,  // 8: coordinator.TCCCoordinator.Commit:output_type -> coordinator.CommitResponse
	7,  // 9: coordinator.TCCCoordinator.Cancel:output_type -> coordinator.CancelResponse
	9,  // 10: coordinator.TCCCoordinator.GetStatus:output_type -> coordinator.StatusResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_coordinator_coordinator_proto_init() }
func file_api_proto_coordinator_coordinator_proto_init() {
	if File_api_proto_coordinator_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_coordinator_coordinator_proto_rawDesc), len(file_api_proto_coordinator_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_coordinator_coordinator_proto_goTypes,
		DependencyIndexes: file_api_proto_coordinator_coordinator_proto_depIdxs,
		MessageInfos:      file_api_proto_coordinator_coordinator_proto_msgTypes,
	}.Build()
	File_api_proto_coordinator_coordinator_proto = out.File
	file_api_proto_coordinator_coordinator_proto_goTypes = nil
	file_api_proto_coordinator_coordinator_proto_depIdxs = nil
}
