// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: branch/branch.proto

package branch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	ResourceData  string                 `protobuf:"bytes,2,opt,name=resource_data,json=resourceData,proto3" json:"resource_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryRequest) Reset() {
	*x = TryRequest{}
	mi := &file_branch_branch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryRequest) ProtoMessage() {}

func (x *TryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_branch_branch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryRequest.ProtoReflect.Descriptor instead.
func (*TryRequest) Descriptor() ([]byte, []int) {
	return file_branch_branch_proto_rawDescGZIP(), []int{0}
}

func (x *TryRequest) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

func (x *TryRequest) GetResourceData() string {
	if x != nil {
		return x.ResourceData
	}
	return ""
}

type TryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryResponse) Reset() {
	*x = TryResponse{}
	mi := &file_branch_branch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryResponse) ProtoMessage() {}

func (x *TryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_branch_branch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryResponse.ProtoReflect.Descriptor instead.
func (*TryResponse) Descriptor() ([]byte, []int) {
	return file_branch_branch_proto_rawDescGZIP(), []int{1}
}

func (x *TryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_branch_branch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_branch_branch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_branch_branch_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmRequest) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

type ConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_branch_branch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_branch_branch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_branch_branch_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_branch_branch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_branch_branch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_branch_branch_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRequest) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_branch_branch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_branch_branch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_branch_branch_proto_rawDescGZIP(), []int{5}
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_branch_branch_proto protoreflect.FileDescriptor

const file_branch_branch_proto_rawDesc = "" +
	"\n" +
	"\x13branch/branch.proto\x12\x06branch\"C\n" +
	"\n" +
	"TryRequest\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\x12#\n" +
	"\rresource_data\x18\x02 \x01(\tR\fresourceData\"=\n" +
	"\vTryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\"\n" +
	"\x0eConfirmRequest\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\"A\n" +
	"\x0fConfirmResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"!\n" +
	"\rCancelRequest\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\"@\n" +
	"\x0eCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xb4\x01\n" +
	"\rBranchService\x12.\n" +
	"\x03Try\x12\x12.branch.TryRequest\x1a\x13.branch.TryResponse\x12:\n" +
	"\aConfirm\x12\x16.branch.ConfirmRequest\x1a\x17.branch.ConfirmResponse\x127\n" +
	"\x06Cancel\x12\x15.branch.CancelRequest\x1a\x16.branch.CancelResponseB\x16Z\x14tcc/api/proto/branchb\x06proto3"

var (
	file_branch_branch_proto_rawDescOnce sync.Once
	file_branch_branch_proto_rawDescData []byte
)

func file_branch_branch_proto_rawDescGZIP() []byte {
	file_branch_branch_proto_rawDescOnce.Do(func() {
		file_branch_branch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_branch_branch_proto_rawDesc), len(file_branch_branch_proto_rawDesc)))
	})
	return file_branch_branch_proto_rawDescData
}

var file_branch_branch_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_branch_branch_proto_goTypes = []any{
	(*TryRequest)(nil),      // 0: branch.TryRequest
	(*TryResponse)(nil),     // 1: branch.TryResponse
	(*ConfirmRequest)(nil),  // 2: branch.ConfirmRequest
	(*ConfirmResponse)(nil), // 3: branch.ConfirmResponse
	(*CancelRequest)(nil),   // 4: branch.CancelRequest
	(*CancelResponse)(nil),  // 5: branch.CancelResponse
}
var file_branch_branch_proto_depIdxs = []int32{
	0, // 0: branch.BranchService.Try:input_type -> branch.TryRequest
	2, // 1: branch.BranchService.Confirm:input_type -> branch.ConfirmRequest
	4, // 2: branch.BranchService.Cancel:input_type -> branch.CancelRequest
	1, // 3: branch.BranchService.Try:output_type -> branch.TryResponse
	3, // 4: branch.BranchService.Confirm:output_type -> branch.ConfirmResponse
	5, // 5: branch.BranchService.Cancel:output_type -> branch.CancelResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_branch_branch_proto_init() }
func file_branch_branch_proto_init() {
	if File_branch_branch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_branch_branch_proto_rawDesc), len(file_branch_branch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_branch_branch_proto_goTypes,
		DependencyIndexes: file_branch_branch_proto_depIdxs,
		MessageInfos:      file_branch_branch_proto_msgTypes,
	}.Build()
	File_branch_branch_proto = out.File
	file_branch_branch_proto_goTypes = nil
	file_branch_branch_proto_depIdxs = nil
}
